language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
git:
  depth: 3 
script:
  - yarn build
notifications:
  email:
    recipients:
      - georgechirivi@yahoo.com
    on_success: always
    on_failu re: always
deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  app: platzi-store-backend 
  on:
    repo: JorgeChirivi/platzi-store-backend

